//! Package the Fumola module library into the wasm binary.
//!
//! The modules under `fumola/` are written in Fumola and are what makes the
//! language useful -- lists, hash maps, level trees, the adapton library
//! itself. A host embedding the runtime has no filesystem to load them from,
//! so their text is compiled in.
//!
//! Generated rather than hand-listed: adding a .fumola file needs no Rust
//! change. Symlinks are followed for content but each path is kept as its own
//! entry, because a module's imports resolve relative to its own directory --
//! that is why `examples/mergeSort/` contains symlinks to `collections/` and
//! `system/`, giving mergeSort its own view of `adapton`.

use std::fs;
use std::path::{Path, PathBuf};

fn collect(dir: &Path, out: &mut Vec<(String, PathBuf, bool)>, root: &Path) {
    let entries = match fs::read_dir(dir) {
        Ok(entries) => entries,
        Err(e) => panic!("cannot read {}: {}", dir.display(), e),
    };
    for entry in entries {
        let entry = entry.expect("readable directory entry");
        let path = entry.path();
        // metadata() follows symlinks, so a symlinked file is a file here and
        // a symlinked directory is walked like any other.
        let meta = match fs::metadata(&path) {
            Ok(meta) => meta,
            // A broken symlink is skipped rather than failing the build.
            Err(_) => continue,
        };
        if meta.is_dir() {
            collect(&path, out, root);
        } else if path.extension().and_then(|e| e.to_str()) == Some("fumola") {
            // Registered under the path Fumola sees, relative to the repo
            // root and without the extension: "fumola/collections/List".
            let relative = path
                .strip_prefix(root)
                .expect("path is under the root")
                .with_extension("");
            let module_path = relative.to_string_lossy().replace('\\', "/");
            // symlink_metadata does not follow the link, so this distinguishes
            // a module's real home from the copies of it that exist only to
            // work around import paths that cannot say "../..". Every path
            // stays registered -- the links are what let mergeSort's imports
            // resolve -- but a host can tell which are duplicates.
            let is_link = fs::symlink_metadata(&path)
                .map(|m| m.file_type().is_symlink())
                .unwrap_or(false);
            out.push((module_path, path, is_link));
        }
    }
}

fn main() {
    let manifest = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").unwrap());
    let root = manifest
        .parent()
        .and_then(|p| p.parent())
        .expect("crate lives two levels below the repo root")
        .to_path_buf();
    let library = root.join("fumola");

    println!("cargo:rerun-if-changed={}", library.display());

    let mut modules: Vec<(String, PathBuf, bool)> = Vec::new();
    collect(&library, &mut modules, &root);
    // Sorted so the generated table does not depend on directory order.
    modules.sort();

    let mut generated = String::new();
    generated.push_str(
        "// Generated by build.rs. Do not edit.\n\
         /// Every module in the Fumola library, as (registered path, source).\n\
         pub static MODULES: &[(&str, &str)] = &[\n",
    );
    for (module_path, file, _) in &modules {
        println!("cargo:rerun-if-changed={}", file.display());
        generated.push_str(&format!(
            "    ({:?}, include_str!({:?})),\n",
            module_path,
            file.display().to_string()
        ));
    }
    generated.push_str("];\n");

    generated.push_str(
        "\n/// The module paths that are symlinks to a module's real home.\n\
         /// They are registered like any other, because a module's imports\n\
         /// resolve relative to its own directory; they are duplicates only\n\
         /// when listing the library for a person to read.\n\
         pub static SYMLINKED: &[&str] = &[\n",
    );
    for (module_path, _, is_link) in &modules {
        if *is_link {
            generated.push_str(&format!("    {:?},\n", module_path));
        }
    }
    generated.push_str("];\n");

    let out = PathBuf::from(std::env::var("OUT_DIR").unwrap()).join("modules.rs");
    fs::write(&out, generated).expect("write the generated module table");
}
